name: Build and Release

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 21
        uses: actions/setup-java@v3
        with:
          java-version:  21
          distribution: 'temurin'

      - name: Install Postgres as dependency to run tests
        run: |
          docker run --name="pg" -e POSTGRES_PASSWORD="pg" -d --net=host cgr.dev/chainguard/postgres:latest
          sleep 60
          docker logs pg
          docker cp ./database/schema.sql pg:/home/postgres
          docker cp ./database/database.sql pg:/home/postgres
          docker exec pg psql -U postgres -f /home/postgres/schema.sql
          docker exec pg psql -U postgres -f /home/postgres/database.sql  

      - name: Run tests and build with Maven if successful
        working-directory: ./
        run: mvn -B package --file pom.xml -DskipTests

      - name: Connect to AWS and copy the application
        working-directory: ./
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.AWS_KNOWN_HOSTS }}
        run: |
          pwd
          ls -la ../
          mkdir -p ~/.ssh/
          printf %s\\n "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          printf %s\\n "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/known_hosts
          ls -la ./target
          ls -la ../CloudCrypt
          scp    -i ~/.ssh/id_rsa target/CloudCrypt-1.0.0-SNAPSHOT.jar ubuntu@ec2-13-213-53-140.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/CloudCrypt
          scp    -i ~/.ssh/id_rsa database/schema.sql ubuntu@ec2-13-213-53-140.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/CloudCrypt
          scp    -i ~/.ssh/id_rsa database/database.sql ubuntu@ec2-13-213-53-140.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/CloudCrypt
          scp    -i ~/.ssh/id_rsa .deploy/aws_push.sh ubuntu@ec2-13-213-53-140.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/CloudCrypt
          ssh    -i ~/.ssh/id_rsa ubuntu@ec2-13-213-53-140.ap-southeast-1.compute.amazonaws.com "chmod +x /home/ubuntu/CloudCrypt/aws_push.sh"
          ssh    -i ~/.ssh/id_rsa ubuntu@ec2-13-213-53-140.ap-southeast-1.compute.amazonaws.com /home/ubuntu/CloudCrypt/aws_push.sh
